      insert into SERVICE (TITLE, SERVICETYPE, INGAMENAME, CREATEDDATE) values ('Best UBER booster RU', 'Boosting', 'RiPmASTer69', '1')
      insert into SERVICE (TITLE, SERVICETYPE, INGAMENAME, CREATEDDATE) values ('T15 Strand rotations', 'Boosting', 'KaomsDick22', '2')
      insert into SERVICE (TITLE, SERVICETYPE, INGAMENAME, CREATEDDATE) values ('T15 Strand rotations', 'Boosting', 'KaomsDick22', '3')
      insert into SERVICE (TITLE, SERVICETYPE, INGAMENAME, CREATEDDATE) values ('T15 Strand rotations', 'Boosting', 'KaomsDick22', '4')
      insert into SERVICE (TITLE, SERVICETYPE, INGAMENAME, CREATEDDATE) values ('T15 Strand rotations', 'Boosting', 'KaomsDick22', '5')